global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080'] # host.docker.internal yerine servis adÄ±

  - job_name: 'user'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['userservice:8081'] # docker-compose'daki container_name

  - job_name: 'role'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['roleservice:8082']

  - job_name: 'permission'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['permissionservice:8083']

  - job_name: 'group'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['groupservice:8084']

  - job_name: 'organization'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['organizationservice:8085']


